
const { Router } = require('express');
const { check } = require('express-validator');
const { usersPost, usersGet, usersGetID, usersTokens } = require('../controllers/users');
const { existEmail, existUser } = require('../helpers/db-validators');
const { validateFields } = require('../middlewares/validate');


const router = Router();

//GET 

router.get('/', usersGet);

//GET BY ID

router.get('/:id', [
    check('id').custom(existUser),
    validateFields
],usersGetID);


//POST
router.post('/',[
    check('name','name is mandatory').not().isEmpty(),
    check('email', 'email is not valid').isEmail(),
    check('emai').custom(existEmail),
    validateFields
], usersPost)



//GET ALL TOKENS GENERATED BY THE USER

router.get('/:id/tokens', usersTokens);


module.exports = router;